# Generated by Django 4.1.13 on 2024-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_change_password",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
