# Generated by Django 4.1.13 on 2024-05-11 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('user', '0002_user_last_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('avatar', 'avatar'), ('user_body', 'exercise'), ('licence', 'licence')], max_length=16)),
                ('body_side', models.CharField(choices=[('front', 'front'), ('back', 'back'), ('left', 'left'), ('right', 'right')], max_length=16)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_media',
                'verbose_name_plural': 'user_medias',
                'db_table': 'user_media',
                'ordering': ['type'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['user'], name='user_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermedia',
            constraint=models.UniqueConstraint(condition=models.Q(('body_side__isnull', False)), fields=('user', 'body_side'), name='unique_user_body_side_when_body_side_not_null'),
        ),
    ]
