from .env_handler import env

SMS_API_KEY = env("SMS_API_KEY")
SMS_OTP_TEMPLATE = env("SMS_OTP_TEMPLATE")
SMS_PASSWORD_TEMPLATE = env("SMS_PASSWORD_TEMPLATE")
SMS_LINE_NUMBER = env("SMS_LINE_NUMBER")
